#!/bin/bash
# Type check everything
# WARN vue-tsc requires @vue/runtime-dom (provided by Vue3 but needed in top level node_modules)
# WARN Keep this list in sync with .eslintrc.js
set -e
cd "$(dirname "$(dirname "$0")")"


npx tsc --noEmit --project collector
npx tsc --noEmit --project client
npx vue-tsc --noEmit --project app
npx vue-tsc --noEmit --project site
