#!/bin/bash
# Auto-generate api docs for client and place within site
set -e
cd "$(dirname "$(dirname "$0")")/site"

./node_modules/.bin/typedoc --out src/access/client/api --tsconfig ../client/tsconfig.json "$@" ../client/src
