#!/bin/bash
# Build client
set -e
cd "$(dirname "$(dirname "$0")")/client"


# Clear existing
rm -rf dist


# Build css
node_modules/.bin/sass --style=compressed src/css/index.sass dist/client.css


# Common args
# NOTE Target must be suitable for browsers as well as Node18+
esbuild="../node_modules/.bin/esbuild --sourcemap --target=es6"


# Build cross-platform ESM with typings (the main format recommended to be used)
# NOTE Not bundling as apps should do themselves, and separate files easier for debugging and types
../node_modules/.bin/tsc --emitDeclarationOnly --outDir dist/esm
$esbuild --format=esm --platform=neutral --outdir=dist/esm ./src/*.ts


# Provide some other formats that may be useful for some people, but not recommended
# NOTE These formats aren't recommended, so not providing types or hosting for them etc.
# NOTE Since package type is "module" then need to use '.cjs' extension to force require syntax
$esbuild --format=cjs  --platform=node    --outdir=dist/cjs --out-extension:.js=.cjs ./src/*.ts
$esbuild --format=esm  --platform=neutral --outfile=dist/bundled.mjs       --bundle --minify src/index.ts
$esbuild --format=iife --platform=browser --outfile=dist/bundled.global.js --bundle --minify src/index.ts
