#!/bin/bash
# Build collector
set -e
cd "$(dirname "$(dirname "$0")")/collector"


../.bin/build_collector

# Also include types (slow so not part of build command)
npx tsc --emitDeclarationOnly --outDir dist
