#!/bin/bash
# Publish quiet app
set -e
cd "$(realpath -m "$0/../..")/app"

# Do fresh build of components app relies on since they're bundled when published
../.bin/build_references
../.bin/build_search
../.bin/build_client

../.bin/build_app_quiet

# Publish to server
npx esbuild --platform=node ../.bin/publish.ts | node --input-type=module - quiet.fetch.bible
