#!/bin/bash
# Setup dev environment
set -e
cd "$(dirname "$(dirname "$0")")"


# This will install modules for all workspaces by default
# They'll be stored in the root node_modules despite being defined in separate package.json files
npm ci
