#!/bin/bash
# Install node
set -e
cd "$(dirname "$0")"

VERSION="25.8.1"

mkdir -p nodejs
curl -fsSL https://nodejs.org/dist/v${VERSION}/node-v${VERSION}-linux-x64.tar.xz \
    | tar -xJ --strip-components=1 -C nodejs node-v${VERSION}-linux-x64

ln -sf nodejs/bin/node node
ln -sf nodejs/bin/npm npm
ln -sf nodejs/bin/npx npx
