#!/bin/bash
# Wipe and rebuild test collection
set -e
cd "$(dirname "$(dirname "$0")")"

# Wipe collection
rm -rf collection
mkdir collection

# Rebuild collector
.bin/build_collector

# Build collection from scratch
.bin/collector setup
.bin/collector discover ebible
.bin/collector download eng_bsb
.bin/collector download vie_vcb
.bin/collector process
